// AuthService
export const SET_AUTHENTICATED_STATUS = 'SET_AUTHENTICATED_STATUS';
export const SET_AUTHENTICATION_ERROR = 'SET_AUTHENTICATION_ERROR';

// User
export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO';
export const SAVE_USER_THREADS = 'SAVE_USER_THREADS';
export const SAVE_ANON_THREAD_ID = 'SAVE_ANON_THREAD_ID';

// ProConModal
export const TOGGLE_PRO_CON_MODAL = 'TOGGLE_PRO_CON_MODAL';
export const ADD_THREAD_INFO_PRO_CON_MODAL = 'ADD_THREAD_INFO_PRO_CON_MODAL';
export const CLEAR_INFO_PRO_CON_MODAL = 'CLEAR_INFO_PRO_CON_MODAL';

// Proposal
export const UPDATE_VISIBLE = 'UPDATE_VISIBLE';

// New Idea
export const SET_NEW_IDEA_VISIBLE = 'SET_NEW_IDEA_VISIBLE';

// Edit Proposal
export const UPDATE_EDIT_PROPOSAL_VISIBLE = 'UPDATE_EDIT_PROPOSAL_VISIBLE';
export const UPDATE_EDIT_THREAD = 'UPDATE_EDIT_THREAD';

// Map
export const UPDATE_PIN_VISIBILITY = 'UPDATE_PIN_VISIBILITY';
export const UPDATE_PIN_POSITION = 'UPDATE_PIN_POSITION';
export const SET_PIN_MODE = 'SET_PIN_MODE';
export const SET_THEME_MODE = 'SET_THEME_MODE';
export const RESET_MAP = 'RESET_MAP';
export const ADD_PROPOSAL_DETAILS = 'ADD_PROPOSAL_DETAILS';
export const UPDATE_POPULAR_HASHTAGS = 'UPDATE_POPULAR_HASHTAGS';
export const TOGGLE_CONFIRMATION = 'TOGGLE_CONFIRMATION';
export const SET_CITY = 'SET_CITY';

// Surveys
export const SAVE_ACTIVE_SURVEYS = 'SAVE_ACTIVE_SURVEYS';

// Searched
export const CHANGE_SHOW_THREADS = 'CHANGE_SHOW_THREADS';
export const SAVE_SEARCHED_THREADS = 'SAVE_SEARCHED_THREADS';
export const SAVE_SEARCHED_THREADS_NUMBER = 'SAVE_SEARCHED_THREADS_NUMBER';
export const UPDATE_TOTAL_THREADS = 'UPDATE_TOTAL_THREADS';
export const HAS_SEARCHED = 'HAS_SEARCHED';

// Best ideas
export const SET_BEST_IDEA_THEME = 'SET_BEST_IDEA_THEME';
export const SET_VOTING_CITY = 'SET_VOTING_CITY';
export const SET_VOTING_USER = 'SET_VOTING_USER';

// Pub talk reg modal
export const TOGGLE_PUB_TALK_REG_MODAL = 'TOGGLE_PUB_TALK_REG_MODAL';
export const SET_SELECTED_PUB_TALK = 'SET_SELECTED_PUB_TALK';
